### ISSUE TITLE
Incompatibility with Ceylon 1.3.3

### ISSUE THREAD

**Issue by davidfestal** [jeancharles-roger/fr.minibilles.cli#1] opened 2017-11-13 21:37 UTC
I'd like to use `fr.minibilles.cli` in a current project, but with the `0.2.0` release of the module available on herd, I get this error when trying to run my program on Ceylon 1.3.3:

```
ceylon run: com.redhat.ceylon.compiler.java.runtime.metamodel.decl.
ClassWithConstructorsDeclarationImpl cannot be cast to ceylon.language.meta.
declaration.ClassWithInitializerDeclaration
java.lang.ClassCastException: com.redhat.ceylon.compiler.java.runtime.metamodel.decl.ClassWithConstructorsDeclarationImpl cannot be cast to ceylon.language.meta.declaration.ClassWithInitializerDeclaration
	at fr.minibilles.cli.parseSingleValue_.parseSingleValue(cli.ceylon:64)
	at fr.minibilles.cli.parseValue_.parseValue(cli.ceylon:32)
	at fr.minibilles.cli.parseArguments_$5$1.$next$1(cli.ceylon:238)
	at fr.minibilles.cli.parseArguments_$5$1.next(cli.ceylon:238)
	at ceylon.language.Array.createArrayFromIterable(Array.java:164)
	at ceylon.language.Array.<init>(Array.java:112)
	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:286)
	at ceylon.language.impl.BaseIterable.sequence(bases.ceylon)
	at fr.minibilles.cli.parseArguments_.parseArguments(cli.ceylon:237)
```

I assume there was some incompatible change in the Ceylon metamodel management since `1.3.1` the version which is used by the module).

Do you plan to create a new version of `fr.minibilles.cli` that would be compatible with Ceylon `1.3.3` ?

**Comment by jeancharles-roger** [comment] 2017-11-13 21:41
I will try to update to 1.3.3. I haven't followed recent Ceylon updates, I hope it won't be much of a problem.

**Comment by davidfestal** [comment] 2017-11-13 21:42
I just forked your repo and cloned it locally. I can create a PR if you want.

**Comment by jeancharles-roger** [comment] 2017-11-13 21:43
Yes, that would be really nice, thanks

**Comment by jeancharles-roger** [comment] 2017-11-13 22:08
I've updated to 1.3.3 and remove two warnings but I don't have the problem in my tests.

Do you have an example that reproduce the problem ?

**Comment by jeancharles-roger** [comment] 2017-11-13 22:16
It's confirmed from my size I don't see a problem. You probably tripped on something new that may never have worked :).

I 've pushed the update, I'll publish a 0.2.1 no herd when your problem is fixed.

Cheers

**Comment by jeancharles-roger** [comment] 2017-11-15 13:49
It works for me :), closing.

**Closed as completed by jeancharles-roger** 2017-11-15 13:49 UTC
